project:
  type: book

# do not show output of code chunks - outside errors
execute:
  echo: false
  warning: false

book:
  title: "Operational Performance"
  author: "EUROCONTROL Performance Review Unit"
  date: today
  chapters:
    - index.qmd
    - 01-intro.qmd
    - 10-ASMA.qmd
  # appendices:
  #  - A1-appendix.qmd

downloads: [pdf, docx]

#bibliography: book.bib   #, packages.bib]

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreport
  docx: default
# epub:
#    cover-image: cover.png